import {
	cilBarChart,
	cilBell,
	cilBook,
	cilBriefcase,
	cilCheckCircle,
	cilCode,
	cilCompass,
	cilGlobeAlt,
	cilInfo,
	cilLayers,
	cilLockLocked,
	cilNotes,
	cilPeople,
	cilPuzzle,
	cilRss,
	cilSearch,
	cilShieldAlt,
	cilSpeedometer,
	cilStar,
	cilTerminal,
	cilWarning,
} from "@coreui/icons";

/** Shared CoreUI icon lookup map — used by DocCard, ChallengeGrid, etc. */
export const CUI: Record<string, object> = {
	search: cilSearch,
	key: cilLockLocked,
	terminal: cilTerminal,
	globe: cilGlobeAlt,
	shield: cilShieldAlt,
	feed: cilRss,
	compass: cilCompass,
	book: cilBook,
	plug: cilPuzzle,
	alert: cilWarning,
	gauge: cilSpeedometer,
	lock: cilLockLocked,
	box: cilLayers,
	pulse: cilBarChart,
	users: cilPeople,
	bell: cilBell,
	check: cilCheckCircle,
	code: cilCode,
	star: cilStar,
	info: cilInfo,
	notes: cilNotes,
	briefcase: cilBriefcase,
};
