/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.



 - regrouper les choses oriente utilisateur (genre gestion des decisions etc.) dans la partie user guide
 - avoir un item 'profil' de premier level (ou on parle des notifs/plugins)
 - regrouper central et local api (? hes:bof)
 - regrouper : dashboard et observability
 - dupliquer des liens vers le format de config des parsers/scenarios/... entre la partie "parsers" et la partie "configuration files format"


 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  tutorialSidebar: [

    {
      type: "doc",
      id: "intro"
    },
    {
      type: 'doc',
      label: 'Concepts',
      id: "concepts"
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: ["getting_started/install_crowdsec", "getting_started/crowdsec_tour"]
    },
    {
      type: 'category',
      label: 'User Guides',
      items: ["user_guides/hub_mgmt", "user_guides/decisions_mgmt", "user_guides/bouncers_configuration", "user_guides/machines_mgmt", "user_guides/lapi_mgmt","user_guides/building", "user_guides/replay_mode"]
    },
    {
      type: 'category',
      label: 'Data Sources',
      items: ["data_sources/intro", "data_sources/file", "data_sources/journald", "data_sources/cloudwatch", "data_sources/syslog", "data_sources/troubleshout" ]
    },
    {
      type: 'category',
      label: 'Parsers',
      items: ["parsers/intro", "parsers/format", "parsers/debug","parsers/create", "parsers/enricher", "parsers/patterns"]
    },
    {
      type: 'category',
      label: 'Scenarios',
      items: ["scenarios/intro", "scenarios/format", "scenarios/simulation","scenarios/create" ]
    },
    {
      type: 'category',
      label: 'Collections',
      items: ["collections/intro", "collections/format"]
    },
    {
      type: 'category',
      label: 'Whitelists',
      items: ["whitelist/intro", "whitelist/format", "whitelist/create" ]
    },
    {
      type: 'category',
      label: 'Profiles',
      items: ["profiles/intro", "profiles/format","profiles/notif"]
    },
    {
      type: 'category',
      label: 'Observability',
      items: ["observability/intro", "observability/cscli", "observability/prometheus", "observability/dashboard", "observability/console"]
    },
    {
      type: 'category',
      label: 'Notification',
      items: ["notification/intro"]
    },   
    {
      type: 'category',
      label: 'Configuration',
      items: ["configuration/crowdsec_configuration", "configuration/network_management"]
    },
    {
      type: 'category',
      label: 'Local API',
      items: ["local_api/intro", "local_api/database" , "local_api/bouncers", {"type":"link", "label": "Swagger", "href":"https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI"}]
    },
    {
      type: 'category',
      label: 'Central API',
      items: ["central_api/intro", {"type":"link", "label": "Swagger", "href":"https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=CAPI"}]
    },
    {
      type: 'category',
      label: 'Expr',
      items: ["expr/helpers", "expr/event", "expr/alert", "expr/decision"]
    },
    {
      type: 'category',
      label: 'Bouncers',
      items: ["bouncers/intro", "bouncers/firewall", "bouncers/nginx", "bouncers/custom"]
    },
    {
      type: 'category',
      label: 'CLI reference (cscli)',
      items: ["cscli/cscli_alerts", "cscli/cscli_bouncers", "cscli/cscli_capi", "cscli/cscli_collections",
        "cscli/cscli_completion", "cscli/cscli_config", "cscli/cscli_console", "cscli/cscli_dashboard", "cscli/cscli_decisions", "cscli/cscli_hub", "cscli/cscli_lapi",
        "cscli/cscli_machines", "cscli/cscli_metrics", "cscli/cscli_parsers", "cscli/cscli_postoverflows", "cscli/cscli_scenarios", "cscli/cscli_simulation", "cscli/cscli_version"]
    },
    {
      type: 'category',
      label: 'Contributing',
      items: ["contributing/contributing_test_env", "contributing/contributing_code", "contributing/contributing_hub", "contributing/contributing_bouncers" , "contributing/contributing_doc"]
    },
    {
      type: 'doc',
      label: 'Console',
      id: "console"
    },
    {
      type: 'doc',
      label: 'Contact the team',
      id: "contact_team"
    },
    {
      type: 'doc',
      label: 'About this documentation',
      id: "about_docs/documentation_about"
    },
  ],
};
