/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    preflight: false,
  },
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/**/*.{js,jsx,ts,tsx,mdx}",
    "./unversioned/**/*.{js,jsx,ts,tsx,mdx}",
    "./versioned_docs/**/*.{js,jsx,ts,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "cs-bg":          "var(--cs-bg)",
        "cs-bg-soft":     "var(--cs-bg-soft)",
        "cs-surface":     "var(--cs-surface)",
        "cs-surface-2":   "var(--cs-surface-2)",
        "cs-border":      "var(--cs-border)",
        "cs-border-hi":   "var(--cs-border-hi)",
        "cs-ink":         "var(--cs-ink)",
        "cs-ink-dim":     "var(--cs-ink-dim)",
        "cs-ink-mute":    "var(--cs-ink-mute)",
        "cs-orange":      "var(--cs-orange)",
        "cs-orange-soft": "var(--cs-orange-soft)",
        "cs-teal":        "var(--cs-teal)",
        "cs-violet":      "var(--cs-violet)",
        "cs-blue":        "var(--cs-blue)",
        "cs-pink":        "var(--cs-pink)",
        "cs-red":         "var(--cs-red)",
        "cs-btn-text":    "var(--cs-btn-text)",
        primary: `rgb(var(--primary) / <alpha-value>)`,
        "primary-foreground": `rgb(var(--primary-foreground) / <alpha-value>)`,
        secondary: `rgb(var(--secondary) / <alpha-value>)`,
        "secondary-foreground": `rgb(var(--secondary-foreground) / <alpha-value>)`,
        info: `rgb(var(--info) / <alpha-value>)`,
        "info-foreground": `rgb(var(--info-foreground) / <alpha-value>)`,
        premium: `rgb(var(--premium) / <alpha-value>)`,
        gray: {
          50: `rgb(var(--color-gray-50) / <alpha-value>)`,
          100: `rgb(var(--color-gray-100) / <alpha-value>)`,
          200: `rgb(var(--color-gray-200) / <alpha-value>)`,
          300: `rgb(var(--color-gray-300) / <alpha-value>)`,
          400: `rgb(var(--color-gray-400) / <alpha-value>)`,
          500: `rgb(var(--color-gray-500) / <alpha-value>)`,
          600: `rgb(var(--color-gray-600) / <alpha-value>)`,
          700: `rgb(var(--color-gray-700) / <alpha-value>)`,
          800: `rgb(var(--color-gray-800) / <alpha-value>)`,
          900: `rgb(var(--color-gray-900) / <alpha-value>)`,
          950: `rgb(var(--color-gray-950) / <alpha-value>)`,
        },
        danger: `rgb(var(--color-red) / <alpha-value>)`,
        border: `rgb(var(--border) / <alpha-value>)`,
        ring: `rgb(var(--color-primary) / <alpha-value>)`,
        background: `rgb(var(--background) / <alpha-value>)`,
        foreground: `rgb(var(--foreground) / <alpha-value>)`,
        success: `rgb(var(--color-green) / <alpha-value>)`,
        platinum: `rgb(var(--color-platinum) / <alpha-value>)`,
        card: `rgb(var(--card) / <alpha-value>)`,
        "card-foreground": `rgb(var(--card-foreground) / <alpha-value>)`,
      },
      backgroundImage: () => ({
        landing: "url('/img/landing-page-bg.webp')",
      }),
      fontFamily: {
        "cs-sans": ["var(--cs-font-sans)"],
        "cs-mono": ["var(--cs-font-mono)"],
      },
      scale: {
        99: "0.99",
        101: "1.01",
      },
    },
  },
  safelist: [
    {
      pattern: /invert(-0)?/,
      variants: ["dark", "light", "before"],
    },
  ],
  plugins: [require("tailwindcss-animate")],
  prefix: "", // This is the prefix for the tailwind classes to not clash with docusarus classes
};
